//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Approved_180623
    {
        public string Name { get; set; }
        public string status { get; set; }
    
        public virtual JobSeeker_180623 JobSeeker_180623 { get; set; }
    }
}
