//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobSeeker_180623
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JobSeeker_180623()
        {
            this.Resume_180623 = new HashSet<Resume_180623>();
        }
    
        public string Name { get; set; }
        public string Password { get; set; }
        public string Emailid { get; set; }
        public string MobileNo { get; set; }
        public string Location { get; set; }
        public byte[] photo { get; set; }
        public string Position { get; set; }
        public string Experience { get; set; }
        public string PreferredJobLocation { get; set; }
        public string Skills { get; set; }
        public Nullable<System.DateTime> Dateofapplication { get; set; }
        public byte[] Resume { get; set; }
        public string Status { get; set; }
    
        public virtual Approved_180623 Approved_180623 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Resume_180623> Resume_180623 { get; set; }
    }
}
